blog/urls.py
from django.urls import path
from .views import (
    PostDetailView,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView
)
from . import views

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='blog_home'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('new/', PostCreateView.as_view(), name='post_create'),
    path('<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
]

schoolly/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve






urlpatterns = [
    path('admin/', admin.site.urls),
    path('curriculum/', include('curriculum.urls', namespace='curriculum')),
    path('', include('pages.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('users/', include('users.urls', namespace='users')),
   
    path('results/', include('results.urls', namespace='results')),
    path('students/', include('students.urls', namespace='students')),
    path('staff/', include('staff.urls', namespace='staff')),

    path('attendance/', include('attendance.urls', namespace='attendance')),
    path('demoschool/', include('demoschool.urls', namespace='demoschool')),
    path('portal/', include('portal.urls', namespace='portal')),
    path('quizes/', include('quizes.urls', namespace = 'quizes')),
    path('blog/', include('blog.urls', namespace = 'blog')),
    path('notification/', include('notification.urls', namespace = 'notification')),
    # path('demoschool/', include('demoschool.urls')),

    # path('ckeditor', include('ckeditor_uploader.urls')),    #for ckeditor image upload

    

#PATH FOR DOWNLOAD URL
   url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),

  


    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from students import views as user_views 
from django.contrib.auth import views as auth_views
from students.views import (StudentListView,
                            StudentDetailView,
                            StudentCreateView,
                            StudentUpdateView,
                            StudentDeleteView,
                            MyStudentList,
)

app_name = 'students'

urlpatterns = [
    path('student-page/', user_views.studentpage, name="studentpage"),
    path('student-form/', user_views.studentupdateform, name="studentform"),
    path('', user_views.studentlist, name="student-list"),
    # path('pdf/<pk>/', user_views.student_render_pdf_view, name="student-pdf-view"),
    path('student-list/', StudentListView.as_view(), name="all-students"),
    path('<int:id>/', StudentDetailView.as_view(), name="students-detail"), 
    path('new/', StudentCreateView.as_view(), name="students-create"),
    path('<int:id>/update/', StudentUpdateView.as_view(), name="students-update"),
    path('<int:id>/delete/', StudentDeleteView.as_view(), name="students-delete"),  

    path('pdf/<pk>/', user_views.student_render_pdf_view, name="student-pdf-view"),
    path('test-view/', user_views.render_pdf_view, name="test-view"),

    path('student-pdf', user_views.mystudent_pdf, name="student-pdf"),
    path('student-csv', user_views.mystudent_csv, name="student-csv"),

    #for my rest_framework
    path('api-auth/', MyStudentList.as_view(), name="apiview"),
    
 


]

users/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views 
from django.contrib.auth import views as auth_views


app_name ='users'

urlpatterns = [
    path('register/', user_views.register, name="register"),
    path('student-staff/', user_views.student_staff, name="student_staff"),
    # path('login/', user_views.user_login, name="login"),
    path('dashboard/', user_views.users_home, name="users-dashboard"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('profile/', user_views.profile, name="profile"),
    path('logout/', user_views.user_logout, name='user_logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name="password_reset_confirm"),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name="password_reset_complete"),
    
   
]

students/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Mystudents, StudentDetail


class StudentProfileForm(forms.ModelForm):

    class Meta:
        model = Mystudents
        fields = '__all__'


class StudentUpdateForm(forms.ModelForm):

    class Meta:
        model = StudentDetail
        fields = '__all__'

students/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib import messages
#converting html to pdf
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from students.models import StudentDetail
from students.forms import StudentUpdateForm
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter
from django.http import FileResponse
import csv
# for my rest_framework
from .serializers import StudentDetailSerializer
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from .filters import StudentFilter
from django_filters.views import FilterView


# @login_required
@login_required
def studentupdateform(request):
    if request.method == 'POST':
        su_form = StudentUpdateForm(request.POST)
        #
      
        if su_form.is_valid():    #and sa_form.is_valid():
            su_form.save()
         #
            
            messages.success(request, f'Your account has been updated successfully')
            return redirect('profile')
    else:
         su_form = StudentUpdateForm()
        #
       
            
    context = {
        'su_form': su_form,
        #
   
    }

    return render(request, 'students/student_register_form.html', context)


@login_required
def studentlist(request):
    studentlist = StudentDetail.objects.all()
    studentdetail_filter = StudentFilter(request.GET, queryset=studentlist) 
    studentlist = studentdetail_filter.qs

    context = {
        'studentlist' : studentlist,
        'studentdetail_filter': studentdetail_filter,
       

    }
    return render (request, 'students/student_list.html', context)



class StudentListView(LoginRequiredMixin, ListView):
    context_object_name = 'students'
    model = StudentDetail
    queryset = StudentDetail.objects.all()
    template_name = 'students/student_list.html'
    paginate_by = 2
    filterset_class = StudentFilter
    


class StudentDetailView(DetailView):  
    model = StudentDetail
    template_name = 'students/student_detail_view.html'
    # queryset = User.objects.all()
    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(StudentDetail, id=id_)


# I am using function base view as above instead of this
class StudentCreateView(LoginRequiredMixin, CreateView):
    form_class = StudentUpdateForm
    template_name = 'students/student_register_form.html'
    # queryset= StudentDetail.objects.all()

    # success_url = '/'
    def form_valid(self, form):
        return super().form_valid(form)



class StudentUpdateView(LoginRequiredMixin, UpdateView):
    form_class = StudentUpdateForm
    template_name = 'students/student_form.html'
    # queryset = StudentDetail.objects.all()


    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(StudentDetail, id=id_)

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)

class StudentDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'students/student_delete.html'
    success_url = '/'
    
    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(StudentDetail, id=id_)
    # queryset = StudentDetail.objects.all()

    
    
    



def student_render_pdf_view(request, *args, **kwargs):    

    pk = kwargs.get('pk')
    
    student = get_object_or_404(StudentDetail, pk=pk)
    template_path = 'students/pdf2.html'
    context = {'student': student}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    # if you want to download
    # response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # if you just want to display
    response['Content-Disposition'] = 'filename="report.pdf"'

    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
    html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
        return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response



# redering pdf function
def render_pdf_view(request):
    template_path = 'students/pdf1.html'
    context = {'myvar': 'this is your template context'}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    # if you want to download
    #response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # if you just want to display
    response['Content-Disposition'] = 'filename="report.pdf"'

    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response


def studentpage(request):

    return render(request, 'students/student_page.html', {})


# @login_required
# def studentlist(request):
#     context = {
#         'studentlist':StudentAcademicInfo.objects.all()
#     }

    
#     return render(request, 'students/student_list.html', {})




# #@login_required
# def studentlist(request):
#     studentlist = Mystudents.objects.all()
#     context = {
#         'studentlist' : studentlist

#    }
#     return render (request, 'students/student_list.html', context)



# Generate a PDF staff list
def mystudent_pdf(request):
    # create Bytestream buffer
    buf = io.BytesIO()
    #create a canvas
    c = canvas.Canvas(buf, pagesize=letter, bottomup=0)
    # create a text object
    textob = c.beginText()
    textob.setTextOrigin(inch, inch)
    textob.setFont("Helvetica", 12)
    # Add some lines of text
    # lines = [
    #     "This is line 1",
    #     "This is line 2",
    #     "This is line31",
    #     "This is line 4",
    # ]
    # Designate the model
    student = StudentDetail.objects.all()

    # Create a blank list
        
    lines = [" Student List Report"]

    for students in student:
        lines.append(""),
        lines.append("Username: " + students.user.username),
        lines.append("Current Class: " + str(students.current_class)),
        lines.append("Class Teacher: " + str(students.class_teacher.user.username)), 
        lines.append("Student Type: " + students.student_type),
        lines.append("-------------------------------------"),


    # loop
    for line in lines:
        textob.textLine(line)
    #fininsh up
    c.drawText(textob)
    c.showPage()
    c.save()
    buf.seek(0)
    # Return something
    return FileResponse(buf, as_attachment=False, filename='students.pdf')


# Generate a CSV staff list
def mystudent_csv(request):
    response = HttpResponse(content_type ='text/csv')
    response['Content-Disposition'] = 'attachment; filename=student.csv'
    
# Create a csv writer
    writer = csv.writer(response)

    student = StudentDetail.objects.all()
    
    # Add column headings to the csv files
    writer.writerow(['Student Name', 'Class Teacher', 'Current Class', 'Student Type'])


    # Loop thru and output
    for students in student:
        writer.writerow([students.user.username, students.current_class, students.class_teacher, students.student_type])
        
    return response


# for rest framework
class MyStudentList(APIView):
    def get(self, request):
        students1 = StudentDetail.objects.all()
        serializer = StudentDetailSerializer(students1, many=True)
        return Response(serializer.data)

    def post(self):
        pass




def studentupdate(request):
    if request.method == 'POST':
        student_form = StudentUpdateForm(request.POST)
       
        if student_form.is_valid():
            student_form.save()
            messages.success(request, f'Your profile has been updated successfully')
            return redirect('profile')
    else:
        student_form = StudentUpdateForm()
       

    context = {
        'student_form': student_form,

    }

    return render(request, 'users/student_update_form.html', context)

students/templates/students/main.html
<html>
    <head>
        <meta charset ='utf-8'>
        <title>PDF Main</title>
    </head>
    <body>
        
        {% for student in object_list %}
        <a href="{% url 'students:students-detail' student.user.pk %}"> {{ student.user.username}}</a><br>
        {{ student.user.studentdetail.current_class }}<br />
        {{ student.user.studentdetail.class_teacher }}<br />
        <a href="{% url 'students:student-pdf-view' student.pk % }"> <button class="btn btn-prmary"> pdf </button></a><br />
        <hr>


        {% endfor %}
       
      
    </body>
    </html>

students/templates/students/pdf1 copy.html
<html>
    <head>
        <meta charset ='utf-8'>
        <title>PDF test</title>
    </head>
    <body>
        {{ student }}
    </body>
    </html>

students/templates/students/pdf1.html
<html>
    <head>
        <meta charset ='utf-8'>
        <title>PDF test</title>
    </head>
    <body>
        {{ myvar }}
    </body>
    </html>

students/templates/students/pdf2.html
<html>
    <head>
        <meta charset ='utf-8'>
        <title>Pdf file2</title>
    </head>
    <body>
        {{ student }}<br />
        {{ student.dob }}
    </body>
    </html>

students/templates/students/student_delete.html
{% extends 'portal/portal-home.html' %}
{% load static %}

{% block content_body %}
    <form method="post">
        {% csrf_token %}
        <h2>Are you sure you want to delete this STUDENT?<br>
            USERNAME:<span style="color:red">"{{ object.user }}"</span></h2>
 
        <button class="btn btn-outline-danger" type="submit">Delete Student</button>
        </form>
        <button class="btn btn-outline-info"><a href="{% url 'students:students-detail' object.id  %}">Cancel</a></button>
    </div>

    <body class="vh-100">    
        <div class="authincation h-100">
            <div class="container h-100">
                <div class="row justify-content-center h-100 align-items-center">
                    <div class="col-md-5">
                        <div class="form-input-content text-center error-page">
                            <h2 class="error-text fw-bold">Oops!</h2>
                            <h3>Are you sure you want to delete this STUDENT?<br>
                                USERNAME:<span style="color:red">"{{ object.user }}"</span></h3>
                            <form method="post">
                                {% csrf_token %}
                           
                         
                                <button class="btn btn-danger" type="submit">Delete Student</button>
                                </form>
                        
                            <p>Note: You cannot reverse the delete!</p> 
                            <div>
                                <button class="btn btn-info"><a href="{% url 'students:students-detail' object.id  %}">No! Cancel</a></button>
                            </div>	
                        </div>
                    </div>
                </div>
            </div>
        </div>


    {% endblock content_body %}


    {% block scripts %}
    <script src="{% static 'portal/vendor/global/global.min.js' %}"></script>
    <script src="{% static 'portal/js/custom.min.js' %}"></script>
    <script src="{% static 'portal/js/dlabnav-init.js' %}"></script>
    <script src="{% static 'portal/js/styleSwitcher.js' %}"></script>
    {% endblock scripts %}

students/templates/students/student_list.html
{% extends 'portal/portal-home.html'%}
{% load crispy_forms_tags %}
{% load static %}

{% block content_body %}

		<div class="content-body">
			<!-- row -->
			<div class="container-fluid">
				<div class="d-flex justify-content-between align-items-center flex-wrap">
					<div class="card-action coin-tabs mb-2">
						
						<ul class="nav nav-tabs" role="tablist">
							<li class="nav-item">
								<a class="nav-link"href="{% url 'students:student-pdf' %}">View PDF</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="{% url 'students:student-csv' %}">Download CSV</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" data-bs-toggle="tab" href="#Booked">Graduated</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" data-bs-toggle="tab" href="#Canceled">Expelled</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" data-bs-toggle="tab" href="#Refund">Dropped</a>
							</li>
						</ul>
					</div>
					<div class="d-flex align-items-center mb-2 flex-wrap"> 
						<div class="guest-calendar">
							<div id="reportrange" class="pull-right reportrange" style="width: 100%">
								<span>Students List</span><b class="caret"></b>
								<i class="fas fa-chevron-down ms-3"></i>
							</div>
						</div>
						<div class="newest ms-3">
							<select class="default-select">
								<option>Newest</option>
								<option>Oldest</option>
							</select>
						</div>	
					</div>
				</div>
<!-- 				
					<button class="btn btn-outline-info" > <a href="{% url 'students:student-pdf' %}">PDF Format</a></button>
					<button class="btn btn-outline-info" > <a href="{% url 'students:student-csv' %}">CSV Format</a></button> -->


							<div class="row">
								<div ">	
									<div>

										<div style="float:left; padding:4px; width:30%;">
											<div><form>
											
												{{ studentdetail_filter.form|crispy}}
												
												<button class="btn btn-outline-secondary btn-sm mb-1 mt-1" type="submit">Filter by Class Teacher </button>
											</form>	</div>
										</div>
										
										<div style="float:left; padding:4px; width:30%;">
											<div ><form>
											
												{{ studentdetail_filter.form|crispy}}
												
												<button class="btn btn-outline-secondary btn-sm mb-1 mt-1" type="submit">Filter by Status</button>
											</form>	</div>
										</div>
										<div style="float:left; padding:4px; width:30%;">
											<div ><form>
											
												{{ studentdetail_filter.form|crispy}}
												
												<button class="btn btn-outline-secondary btn-sm mb-1 mt-1" type="submit">Filter by Current Class</button>
											</form>	</div>
										</div>
										
									  </div>		
					
					
			
					</div>
					</div>

					
				

				
					<div class="col-xl-12">
						<div class="card">
							
							<div class="card-body p-0">
								<div class="tab-content">	
									<div class="tab-pane active show" id="AllGuest">
										<div class="table-responsive">
											<table class="table card-table display mb-4 shadow-hover default-table table-responsive-lg" id="guestTable-all">
												<thead>
													<tr>
														<th class="bg-none">
															<div class="form-check style-1">
															  <input class="form-check-input" type="checkbox" value="" id="checkAll">
															</div>
														</th>
														<th>Student ID</th>
														<th>Admin Date</th>
														<th class="text-center">Class</th>
														<th class="text-center">Teacher ID</th>
														<th>Parent</th>
														
														<th class="text-center">Status</th>
													
														
													</tr>
												</thead>
												<tbody>
													{% for student in students %}
													<tr>
														<td>
															<div class="form-check style-1">
															  <input class="form-check-input" type="checkbox" value="">
															</div>
														</td>
														<td>
															<div class="concierge-bx d-flex align-items-center">
																<img class="me-3 rounded" src="{{user.profile.image.url}}" alt="">
																<div>
																	<h5 class="fs-16 mb-0 text-nowrap"><a class="text-black" href="{% url 'students:students-detail' student.pk %}">{{ student.user.username}}</a></h5>
																	<span class="text-primary fs-14">{{ student.user.first_name}} {{ student.user.last_name}}</span>
																</div>
															</div>
														</td>
														<td class="text-nowrap">
															<span>{{ student.user.studentdetail.date_admitted}}</span>
														</td>
														<td>
															<div>
																<h5 class="text-nowrap">{{ student.user.studentdetail.current_class}}</h5>
																
															</div>
														</td>
														<td>
															<div class="text-center">
																<h5 class="text-nowrap">{{ student.user.studentdetail.class_teacher }}</h5>
																<span></span>
															</div>
														</td>
														<td>
														<div>
															<h5 class="text-nowrap">{{ student.user.studentdetail.parent_phone }}</h5>
															<span></span>
														</div>
														
														</td>
														
														<td>
															<div class="text-center">
																{% if student.user.studentdetail.student_status == 'active' %}
																<span style="color:green"><b><i>Active</i></b></span>		
															
																{% elif student.user.studentdetail.student_status == 'dropped' %}
																<span style="color:red"><b><i>Dropped</i></b></span>	
																{% elif student.user.studentdetail.student_status == 'graduated' %}
																<span style="color:green"><b><i>Graduated</i></b></span>	
																{% elif student.user.studentdetail.student_status == 'expelled' %}
																<span style="color:grey"><b><i>Expelled</i></b></span>	
															</div>
														
														
															{% endif %}
														</td>
														
														
														{% endfor %}
													</tr>	
												</tbody>
											</table>
													
												

				{% if is_paginated %}

              {% if page_obj.has_previous%}
                <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}
                {% for num in page_obj.paginator.page_range %}
                 
                {% if page_obj.number == num %}
                  <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                  {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                  <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                  {% endif %}
                  
                  {% endfor %}
                 
                  {% if page_obj.has_next %}
                  <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number}}">Next</a>
                  <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                  {% endif %}

            {% endif %}
	
	



										</div>	
									</div>	
									
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	
		{% endblock content_body %}
		<!--**********************************
			

students/templates/students/student_list1.html
{% extends 'users/user_dashboard.html'%}

{% block content %}
<div class="col-lg-10">
<div class="card mb-4">
    <div class="card-header">
        Student List
    </div>
    <div class="card-body">   

        {% if user.is_superuser or user.profile.user_type == 'parent' %}
        <div style="margin-bottom:10px">
            <button class="btn btn-outline-info" > <a href="{% url 'students:student-pdf' %}">PDF Format</a></button>
            <button class="btn btn-outline-info" > <a href="{% url 'students:student-csv' %}">CSV Format</a></button>
                </div>
        <div class="table-responsive-sm">
        <table class = "table" >
            <thead class="thead-light">
            <tr>
              <th>Username</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Current Class</th>
              <th>F.Teacher</th>
              <th>Stud. Type</th>
              <th>Contact</th>
             
            </tr>
        </thead>
            {% for s in student %}
            <tbody>
            <tr>
              <th><a href="#"> {{ s.user.username}}</a></th>
              <th> {{ s.user}}</th>
              <th> {{ s.dob}}</th>
              <th> {{ s.date_admitted}}</th>
              <th> {{ s.user.studentdetail.class_teacher}}</th>
              <th> {{ s.user.studentdetail.student_type}}</th>
              <th> {{ s.user.studentdetail.parent_phone}}</th>
              
            </tr> 
        </tbody>
            {% endfor %}
            </table>
        </div>
        
        
    
    {% comment %} {% endfor %} {% endcomment %}
    {% else %}
    <h1> Oops! You do not have permission to view this resource</h1>
    
    {% endif %} 
      
</div>
</div>
</div>
</div>
</div>
{% endblock content %}

students/templates/students/student_page.html
{% extends 'users/user_dashboard.html'%}
{% block content %}

hello:  {{ user.username }} <br />
Name :<b>  - {{ user.first_name }} - {{ user.profile.middle_name }} - {{ user.last_name }}</b><br />
Your Gender: {{ user.profile.gender }}<br />
Your are a - {{ user.studentacademicinfo.student_type }}<br />

Your Class On admission: {{ user.studentprofile.class_on_admission }}--<br />
Admission Date: {{ user.studentprofile.date_admitted }}--<br />
{{ user.studentacademicinfo.current_class }}<br />
{{ user.studentacademicinfo.class_teacher }}<br />


{% endblock content%}

students/templates/students/student_profile.html
{% block content %} {

<form method="POST" enctype="multipart/form-data" >
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Profile Info</legend>
            {{ su_form.as_p }}
            {{ sa_form.as_p }}
      
     </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Update</button>
        </div>
    </form>


 </div> 
 {% endblock content %}

students/templates/students/student_register_form.html
 {% extends 'portal/portal-home.html' %}
 {% load crispy_forms_tags %}
 {% load static %}
 
 {% block title %}Student Register {% endblock title %}

 {% block content_body %}

<div class="content-body">
    <div class="container-fluid">
        <div class="row page-titles">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active"><a href="javascript:void(0)">Register New Students</a></li>
                <li class="breadcrumb-item"><a href="#">Read the instruction below</a></li>
            </ol>
        </div>
        <div class="row">
            <div class="col-xl-6">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">Instruction</h5>
                    </div>
                    <div class="card-body">
                        <p class="card-text"> - The form on this page provides inputs for updating registered user to student status<br>
                            - To register a new student, you must first <a href="{% url 'users:register'%}"><b><span style="color:black">register</span></b></a> the student as a user<br>
                           -  Complete the form on this page if you have already registered the student as a new user
                        </p>
                    </div>
                    <div class="card-footer d-sm-flex justify-content-between align-items-center">
                        <div class="card-footer-link mb-4 mb-sm-0">
                           
                        </div>

                        
                    </div>
                </div>
            </div>
            <div class="col-xl-6">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">New Student Registration</h5>
                    </div>
                    <div class="card-body">
                        <p class="card-text">
                            <form method="POST" enctype="multipart/form-data" >
                                {% csrf_token %}
                            
                            {{ form|crispy }}</p>
                    </div>
                    <div class="card-footer d-sm-flex justify-content-between align-items-center">

                        <button type="submit" value="submit" class="btn btn-primary">Register Student</button>
                    
                    </div>
                </form>
                </div>
            </div>
       
          
            </div>
            </div>


        </div>
    </div>
</div>
{% endblock content_body %}


{% block scripts %}
<script src="{% static 'portal/vendor/global/global.min.js' %}"></script>
<script src="{% static 'portal/vendor/jquery-nice-select/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'portal/js/custom.min.js' %}"></script>
<script src="{% static 'portal/js/dlabnav-init.js' %}"></script>
<script src="{% static 'portal/js/demo.js' %}"></script>
<script src="{% static 'portal/js/styleSwitcher.js' %}"></script>
{% endblock scripts %}