blog/urls.py
from django.urls import path
from .views import (
    PostDetailView,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView
)
from . import views

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='blog_home'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('new/', PostCreateView.as_view(), name='post_create'),
    path('<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
]

curriculum/urls.py
from django.urls import path
from . import views


app_name = 'curriculum'

urlpatterns = [
    path('', views.StandardListView.as_view(), name='standard_list'),
    path('<slug:slug>/', views.SubjectListView.as_view(), name='subject_list'),
    path('<str:standard>/<slug:slug>/', views.LessonListView.as_view(), name='lesson_list'),
    path('<str:standard>/<str:slug>/create/', views.LessonCreateView.as_view(), name='lesson_create'),
    path('<str:standard>/<str:subject>/<slug:slug>/', views.LessonDetailView.as_view(), name='lesson_detail'),
    path('<str:standard>/<str:subject>/<slug:slug>/update/', views.LessonUpdateView.as_view(), name='lesson_update'),
    path('<str:standard>/<str:subject>/<slug:slug>/delete/', views.LessonDeleteView.as_view(), name='lesson_delete'),

    
]

schoolly/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve






urlpatterns = [
    path('admin/', admin.site.urls),
    path('curriculum/', include('curriculum.urls', namespace='curriculum')),
    path('', include('pages.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('users/', include('users.urls', namespace='users')),
   
    path('results/', include('results.urls', namespace='results')),
    path('students/', include('students.urls', namespace='students')),
    path('staff/', include('staff.urls', namespace='staff')),

    path('attendance/', include('attendance.urls', namespace='attendance')),
    path('demoschool/', include('demoschool.urls', namespace='demoschool')),
    path('portal/', include('portal.urls', namespace='portal')),
    path('quizes/', include('quizes.urls', namespace = 'quizes')),
    path('blog/', include('blog.urls', namespace = 'blog')),
    path('notification/', include('notification.urls', namespace = 'notification')),
    # path('demoschool/', include('demoschool.urls')),

    # path('ckeditor', include('ckeditor_uploader.urls')),    #for ckeditor image upload

    

#PATH FOR DOWNLOAD URL
   url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),

  


    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

curriculum/models.py
from enum import unique
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
# from ckeditor.fields import RichTextField
# from ckeditor_uploader.fields import RichTextUploadingField


import os
from embed_video.fields import EmbedVideoField

from django.urls import reverse


class Standard(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(null=True, blank=True)
    description = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)



def save_subject_image(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get file name
    if instance.user.username:
        filename = 'Subject_Pictures/{}.{}'.format(instance.subject_id, ext)
    return os.path.join(upload_to, filename)

class Subject(models.Model):
    subject_id = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100)
    slug = models.SlugField(null=True, blank=True)
    standard = models.ForeignKey(Standard, on_delete=models.CASCADE, related_name='subjects')
    # image = models.ImageField(upload_to=save_subject_image, blank=True, verbose_name='Subject Image')
    description = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.subject_id)
        super().save(*args, **kwargs)


def save_lesson_files(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get file name
    if instance.lesson_id:
        filename = 'lesson_files/{}.{}'.format(instance.lesson_id,instance.lesson_id, ext)
        if os.path.exists(filename):
            new_name = str(instance.lesson_id) + str('1')
            filename = 'lesson_images/{}/{}.{}'.format(instance.lesson_id,new_name, ext)
    
    return os.path.join(upload_to, filename)


class Lesson(models.Model):
    lesson_id = models.CharField(max_length=100, unique=True)
    standard = models.ForeignKey(Standard, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='lessons')
    name = models.CharField(max_length=250)
    position = models.PositiveSmallIntegerField(verbose_name="Chapter no.")
    slug = models.SlugField(null=True, blank=True)
    # video = models.FileField(upload_to=save_lesson_files, verbose_name="video", blank=True, null=True)
    video = EmbedVideoField(blank=True, null=True)
    # video = models.CharField(max_length=500, blank=True)
    # video_url = EmbedVideoField(null=True,blank=True)
    ppt = models.FileField(upload_to='save_lesson_files', verbose_name="Presentation", blank=True)
    Notes = models.FileField(upload_to='save_lesson_files', verbose_name="Notes", blank=True)
    comment = models.CharField(max_length=250)

    class Meta:
        ordering = ['position']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('curriculum:lesson_list', kwargs={'slug':self.subject.slug, 'standard':self.standard.slug})
            

# comment module
class Comment(models.Model):
    lesson_name = models.ForeignKey(Lesson, null=True, on_delete=models.CASCADE, related_name='comments')
    comm_name = models. CharField(max_length=100, blank=True)
    # reply = models.ForeignKey("comment", null=True, blank=True, on_delete=CASCADE, related_name='replies')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField(max_length=500)
    date_added = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.comm_name = slugify("comment by" + "-" + str(self.author) + str(self.date_added))
        super().save(*args, **kwargs)

    def __str__(self):
        return self.comm_name

    class Meta:
        ordering = ['-date_added']


class Reply(models.Model):
    comment_name = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='replies')
    reply_body = models.TextField(max_length=500)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "reply to" + str(self.comment_name.comm_name)

curriculum/forms.py
from xml.etree.ElementTree import Comment
from django import forms
from.models import Lesson, Comment, Reply



class LessonForm(forms.ModelForm):
   
    class Meta:
        
        model = Lesson
        fields = ('lesson_id', 'name', 'position', 'ppt', 'video', 'comment')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

        labels = {"body":"Comment:"}

        widgets = {
            'body': forms.Textarea(attrs={'class':'form-control', 'rows':4, 'cols':70, 'placeholder':"Enter Your Comment"}),
        }

        # def __init__(self, *args, **kwargs):
        #     self.request = kwargs.pop('request', None)
        #     super(CommentForm, self).__init__(*args, **kwargs)


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ('reply_body',)

        widgets = {
            'reply_body': forms.Textarea(attrs={'class':'form-control', 'rows':2, 'cols':10}),
        }


    # def __init__(self, *args, **kwargs):
    #     self.request = kwargs.pop('request', None)
    #     super(ReplyForm, self).__init__(*args, **kwargs)

curriculum/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import(TemplateView, DetailView,
                                ListView, FormView, CreateView, 
                                UpdateView, DeleteView)
from .models import Lesson, Standard, Subject, save_lesson_files
from .forms import CommentForm, LessonForm, ReplyForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


class StandardListView(LoginRequiredMixin, ListView):
    context_object_name = 'standards'
    model = Standard
    # template_name = 'curriculum/class_list.html'
    template_name = 'curriculum/elearning_class.html'

class SubjectListView(DetailView):
    context_object_name = 'standards'
    model = Standard
    template_name = 'curriculum/class_subjects.html'


class LessonListView(DetailView):
    context_object_name = 'subjects'
    model = Subject
    template_name = 'curriculum/course_list.html'


class LessonDetailView(DetailView, FormView):
    context_object_name = 'lessons'
    model = Lesson
    template_name = 'curriculum/lesson-detail.html'
    # for replies to lessons
    form_class = CommentForm
    second_form_class = ReplyForm
    '''
        send two forms to page
        see which one is posted
        take action on the form which is posted
    '''
    def get_context_data(self, **kwargs):
        context = super(LessonDetailView, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class()
        # context['comments] = Comment.objects.filter(id=self.object.id)
        return context


    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if 'form' in request.POST:
            form_class = self.get_form_class()
            form_name = 'form'
        else:
            form_class = self.second_form_class
            form_name = 'form2'

        form = self.get_form(form_class)

        if form_name=='form' and form.is_valid():
            print("comment form is returned")
            return self.form_valid(form)
        elif form_name=='form2' and form.is_valid():
            print("reply form is returned")
            return self.form2_valid(form)

    def get_success_url(self):
        self.object = self.get_object()
        standard = self.object.standard
        subject = self.object.subject
        return reverse_lazy('curriculum:lesson_detail', kwargs={'standard':standard.slug,
                                                            'subject':subject.slug,
                                                            'slug':self.object.slug})

    def form_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm.lesson_name = self.object.comments.name
        fm.lesson_name_id = self.object.id
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

    def form2_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm. comment_name_id = self.request.POST.get('comment.id')
        fm.save()
        return HttpResponseRedirect(self.get_success_url())
            



class LessonCreateView(CreateView):
    form_class = LessonForm
    context_object_name = 'subject'
    model = Subject
    template_name = 'curriculum/lesson_create.html'

    def get_success_url(self):
        self.object = self.get_object()
        standard = self.object.standard
        return reverse_lazy('curriculum:lesson_list',kwargs={'standard':standard.slug, 'slug':self.object.slug})

    def form_valid(self, form, *args, **kwargs):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.created_by = self.request.user
        fm.standard = self.object.standard
        fm.subject = self.object
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

class LessonUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    fields = ('name', 'position', 'video', 'ppt', 'comment')
    model = Lesson
    template_name = 'curriculum/lesson_update_view.html'
    context_object_name = 'lessons'
    
    #function to check if user is the login user
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    #preventing other users from update other people's post
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.created_by:
            return True
        return False


class LessonDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Lesson
    context_object_name = 'lessons'
    template_name = 'curriculum/lesson_delete.html'

    def get_success_url(self):
        standard = self.object.standard
        subject = self.object.subject
        return reverse_lazy('curriculum:lesson_list', kwargs={'standard':standard.slug, 'slug':subject.slug})

#preventing other users from update other people's post
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.created_by:
            return True
        return False

curriculum/templates/curriculum/class_list.html
{% extends 'demoschool/index.html'%}
{% load static %}

{% block section%}
<section class="pop-cour">
    <div class="container com-sp pad-bot-70">
        <div class="row">
            <div class="con-title">
                <h3>E- Learning<span> - Platform</span></h3>
                <h2>All <span>Classes</span></h2>

                {% if user.is_authenticated %}
                 <p>Use the links below to explore courses in each class.</p>
                             
            </div>
        </div>

		
        <div class="row">
			{% for standard in standards %} 
            <div class="col-md-6">
				
				
                <div>
                    <!--POPULAR COURSES-->
                    <div class="home-top-cour">
                        <!--POPULAR COURSES IMAGE-->
						 
						
                        <div class="col-md-3"> <img src="{% static 'demoschool/images/course/sm-1.jpg' %}" alt=""> </div>
                        <!--POPULAR COURSES: CONTENT-->
                        <div class="col-md-9 home-top-cour-desc">
							
							{% comment %} <h3><a href="{% url 'curriculum:subject_list' slug=standard.slug %}"></h3> {% endcomment %}
							 								
						<h3>{{standard.name }}</h3>
								
                        <p>follow the link below to explore the list of subjects in {{standard.name }}</p> <span class="home-top-cour-rat">100%</span>
                            <div class="hom-list-share">
                                <ul>
                                    <li><a href="{% url 'curriculum:subject_list' slug=standard.slug %}">Go to > {{standard.name }}</a> </li>
                                    <li><a href="course-details.html"><i class="fa fa-eye" aria-hidden="true"></i>10 Aavailable</a> </li>
                                    <li><a href="course-details.html"><i class="fa fa-share-alt" aria-hidden="true"></i> 570</a> </li>
                                </ul>
                           
                               
                 
                   
                        </div>
                    </div>
                </div>
            </div>
        </div>
   
	{% endfor %}
    {% else %}
    <p>You must be a registered student to access this area.</p>
     {% endif%}
</section>
	


{% endblock section %}

curriculum/templates/curriculum/lesson-detail.html
{% extends 'portal/portal-home.html'%}
{% load static %}

{% block title %}<title>Student Detail </title>{% endblock title%}




{% block content_body %}

<div class="content-body">
	<div class="container-fluid">
		
		<div class="row page-titles">
			<ol class="breadcrumb">
				<li class="breadcrumb-item active"><a href="javascript:void(0)">{{ lessons.subject }}</a></li>
				<li class="breadcrumb-item"><a href="javascript:void(0)">Topic:  {{ lessons.name }}</b><span> - Class:{{ lessons.standard }}</span></a></li>
			</ol>
		</div>
		
		<!-- row -->
		<div class="row">
			<div class="col-lg-12">
				<div class="card">
					<div class="card-body">
						<div class="email-left-box generic-width px-0 mb-5">
							<div class="p-0">
								{% if user.is_authenticated and user.profile.user_type == 'teacher' or user.is_superuser %}
								
								<!-- <a href="email-compose.html" class="btn btn-primary btn-block">Compose</a> -->
								<p>Use the buttons below to create or update lessons</p>
								<p><a href="{% url 'curriculum:lesson_update' standard=lessons.standard.slug subject=lessons.subject.slug slug=lessons.slug %}" class="btn btn-info">Update Lesson</a><br></p>
								<p><a href="{% url 'curriculum:lesson_delete' standard=lessons.standard.slug subject=lessons.subject.slug slug=lessons.slug %}" class="btn btn-secondary">Delete Lesson</a></p>
								{% else %}
								<p><a href="#">Teacher's Contact</a><br></p>

								{% endif %}
							
							</div>

						</div>
						<div class="email-right-box ms-0 ms-sm-4 ms-sm-0">
							<div class="row">
						
										<div class="read-content">
											<div class="media pt-3 d-sm-flex d-block justify-content-between">
												<div class="clearfix mb-3 d-flex">
													<div class="media-body me-2">
														<h5 class="text-primary mb-0 mt-1"><span style="color:black">Created by: </span> {{ lessons.created_by}}</h5>
														<h5 class="text-primary mb-0 mt-1"><span style="color:black">Created on: </span> {{ lessons.created_at}}</h5>
														
													</div>
												</div>
												<div class="clearfix mb-3">
													<a href="javascript:void()" class="btn btn-primary px-3 my-1 light me-2"><i class="fa fa-reply"></i> </a>
													<a href="javascript:void()" class="btn btn-primary px-3 my-1 light me-2"><i class="fas fa-arrow-right"></i> </a>
													<a href="javascript:void()" class="btn btn-primary px-3 my-1 light me-2"><i class="fa fa-trash"></i></a>
												</div>
											</div>
											<hr>
											<div class="media mb-2 mt-3">
												
												<div class="media-body">
													<h2 class="mb-4">Lesson Details:</h2>
													
													{% if lessons.video %}
													<p class="read-content-email">
														Watch Lesson video here..</p>
												</div>
											</div>
											<div>
												<iframe width="620" height="345" 
												src="{{ lessons.video}}" allowfullscreen>                          
												
												</iframe>                     
											   
											</div>
											{% endif %}
											<div class="read-content-body">
												<p class="mb-2"><strong>Teacher's Highlights:</strong><br><i>Teacher's explanations</i> </p>
												<p class="mb-2">{{ lessons.comment }}
												</p>
												
												<hr>
											</div>
											<div class="read-content-attachment">
												<h6><i class="fa fa-download mb-2"></i> Attachments
													<span>(2)</span></h6>
												<div class="row attachment">
													<div class="col-auto">
														{% if lessons.ppt %}
														<a href="{{ lessons.ppt.url }}"  download="{{ lessons.ppt.url }}" class="text-muted">Download Lesson</a>
													</div>
													<div class="col-auto">
														<a href="{{ lessons.ppt.url }}" class="text-muted">Read Lesson</a>
													</div>
													{% endif %}
												</div>
											</div>
											<hr>
											<div class="mb-3 pt-3">

												
													<h3>Comment Area</h3>
													<div class="">
														
														<h4>Post your comment or question below:</h4>
												<form method="post">
												<div class="">
												{% csrf_token %}
												{{form.as_p}}
												<input type="submit" name="form" value="Add Comment" class="btn btn-primary btn-sm">
												</div>
												</form>
												
												{% for comment in lessons.comments.all %}
												<h4>{{comment.author}}<small><i>Posted on {{comment.date_added}}</i></small></h4>
												<p>{{comment.body}}</p>
												{% for reply in comment.replies.all %}
												<h5>{{reply.author}}<small><i>Posted on {{reply.date_added}}</i></small></h5>
												<p>{{reply.reply_body}}</p>
												
												{% endfor %}
												<!-- form to post reply -->
												
												
												<form method="post">
												
												<input type="hidden", name="comment.id" value="{{comment.id}}">
												<input type="hidden", name="comment.comm_name" value="{{comment.comm_name}}">
												{% csrf_token %}
												{{form2.as_p}}
												<input type="submit" name="form2" value="Add Reply" class="btn btn-warning btn-sm">
												
												</form>
												</div>
												</div>
												
												
												{% endfor %}

								</div>
								</div>
								
							</div>
						</div>
					</div>  
				</div>

{% endblock content_body %}

curriculum/templates/curriculum/lesson_create.html
{% extends 'portal/portal-home.html'%}
{% load embed_video_tags %}

{% load static %}
{% block title %}<title>Schoolly Lesson Creation </title>{% endblock title %}

{% block content_body%}

<div class="content-body">
    <div class="container-fluid">
        <div class="row page-titles">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active"><a href="javascript:void(0)">E-Learning</a></li>
                <li class="breadcrumb-item"><a href="javascript:void(0)">Lesson Creation Form</a></li>
            </ol>
        </div>
        <!-- row -->
        <div class="row">
            <div class="col-xl-10 col-xxl-10">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Create Lesson</h4>
                    </div>
                    <div class="card-body">
                        <div id="smartwizard" class="form-wizard order-create">
                            <ul class="nav nav-wizard">
                                <li>
                                       <p>Complete accordingly to upload your lesson</p>
                               
                            </ul>
                            <div class="tab-content">
                                <!-- <div id="wizard_Service" class="tab-pane" role="tabpanel"> -->
                                    <div class="row">
                                        <div class="col-lg-6 mb-2">
                                            <div class="mb-3">
                                                <form method="post" enctype="multipart/form-data">
                                                    {% csrf_token %}
                                                <label class="text-label form-label">Lesson ID*</label>
                                                <input type="text" name="lesson_id" maxlength="100" required id="id_lesson_id" class="form-control" placeholder="Lesson ID">
                                            </div>
                                        </div>
                                        <div class="col-lg-6 mb-2">
                                            <div class="mb-3">
                                                <label class="text-label form-label">Lesson Name*</label>
                                                <input type="text" name="name" maxlength="250" required id="id_name" class="form-control" placeholder="Lesson Name">
                                            </div>
                                        </div>
                                        <div class="col-lg-6 mb-2">
                                            <div class="mb-3">
                                                <label class="text-label form-label">Chapter No*</label>
                                                <input type="number" name="position" min="0" required id="id_position" class="form-control" placeholder="Chapter Number">
                                            </div>
                                        </div>
                                        <div class="col-lg-6 mb-2">
                                            <div class="mb-3">
                                                <label class="text-label form-label">Other Information*</label>
                                                <!-- <input type="text" name="phoneNumber" class="form-control" placeholder="Other Info" required> -->
                                            </div>
                                        </div>
                                        <div class="col-lg-12 mb-3">
                                      
                                            <div class="mb-3">
                                                <label class="text-label form-label">Lesson Details*</label>
                                                <!-- <input type="text" name="comment" maxlength="250" required id="id_comment" class="form-control"> -->
                                                <textarea type="text" name="comment" maxlength="250" required id="id_comment" class="form-control" rows="4"></textarea>
                                            </div>
                                        </div>
                                        <div class="col-lg-6 mb-2">
                                        <div class=" mb-3">
                                            <label class="text-label form-label">Paste Video Link*</label>
                                                <input type=text name="video" id="id_video" class="form-control">
                                            </div>
											
                                        </div>
                                    </div>
                                    <div class="col-lg-6 mb-2">
                                        <div class="input-group mb-3">
                                            
                                            <div class="form-file">
                                                <label class="text-label form-label">Upload Lesson File</label>
                                                <input type="file" name="ppt" id="id_ppt" class="form-file-input form-control">
                                            </div>
											<span class="input-group-text">File</span>
                                        </div>
                                    </div>
                                      
                                    <div class="col-12">
                                        <button type="submit" name="" value="Submit" class="btn btn-primary mb-2">Create New Lesson</button>
                                    </div>
                                </form>
                                <hr>
                                </div>
                                
                                        
                                    </div>
                                </div>
                                
                                    
                                    
                                    
                                    
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
                
                              


{% endblock content_body %}
{%block scripts%}
<!-- Required vendors -->

<script src="{% static 'portal/vendor/global/global.min.js' %}"></script>

<script src="{% static 'portal/vendor/jquery-steps/build/jquery.steps.min.js' %}"></script>
<script src="{% static 'portal/vendor/jquery-validation/jquery.validate.min.js' %}"></script>
<!-- Form validate init -->
<script src="{% static 'portal/js/plugins-init/jquery.validate-init.js' %}"></script>


<!-- Form Steps -->
<script src="{% static 'portal/vendor/jquery-smartwizard/dist/js/jquery.smartWizard.js' %}"></script>
<script src="{% static 'portalvendor/jquery-nice-select/js/jquery.nice-select.min.js' %}"></script>

<script src="{% static 'portal/js/custom.min.js' %}"></script>
<script src="{% static 'portal/js/dlabnav-init.js' %}"></script>
<script src="{% static 'portal/js/demo.js' %}"></script>
<script src="{% static 'portal/js/styleSwitcher.js' %}"></script>
<!-- <script>
    $(document).ready(function(){
        // SmartWizard initialize
        $('#smartwizard').smartWizard(); 
    });
</script> -->
{% endblock scripts %}
























{% block section%}
<section class="pop-cour">
   
    <div class="container com-sp pad-bot-70">
        <div class="row justify-content-center">
      
        </div>
		
        <div class="row justify-content-center">

            <div class="col-md-6">
              
               
    
                <!--Admin view the lesson, enter classroom-->
                <div>
                  <!--LESSON LIST-->
                  <div class="row justify-content-center">
                    {% comment %} <div class="pg-eve-desc pg-blog-desc"> {% endcomment %}
                    <h3>Create New Lesson</h3>
                    <p>Use the form below to create new lesson for the e-learning platform</p> 
                      
                  <div class="home-top-cour">
                    
                       <div class="col-md-12 home-top-cour-desc">                            
            
                        <form method="post" enctype="multipart/form-data">
                         
                            {% csrf_token %}


                            {{ form.as_p }}
                            <input type="submit" name="" value="Submit">
                           
                        </form>   
                                        
                          
                      </div>
                  </div>
              </div>
          </div>
      </div>
    
</section>


{% endblock section %}

curriculum/templates/curriculum/lesson_delete1.html
{% extends 'demoschool/index.html' %}

{% load static %}

{% block section %}
<div class="container">
<h3>Are you sure you want to delete ?</h3>

<form method="post">
    {% csrf_token %}
    <input type="submit" name="" value="delete">
    <a href="{% url 'curriculum:standard_list'  %}"> Cancel</a>
</form>
<h1></h1>
</div>

{% endblock section %}