blog/urls.py
from django.urls import path
from .views import (
    PostDetailView,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView
)
from . import views

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='blog_home'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('new/', PostCreateView.as_view(), name='post_create'),
    path('<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
]

pages/urls.py
from django.urls import path
from pages import views as page_views

app_name ='pages'

urlpatterns = [

    path('demoschool/', page_views.homepage, name='home'),
    path('', page_views.schoolly_home, name='schoolly_home'),
    path('contact/', page_views.contact, name='contact'),
    path('affiliate/', page_views.affiliate, name='affiliate'),
    path('demo/', page_views.demo, name='demo'),
    # path('pages/', include('pages.urls')),
    
]

schoolly/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve






urlpatterns = [
    path('admin/', admin.site.urls),
    path('curriculum/', include('curriculum.urls', namespace='curriculum')),
    path('', include('pages.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('users/', include('users.urls', namespace='users')),
   
    path('results/', include('results.urls', namespace='results')),
    path('students/', include('students.urls', namespace='students')),
    path('staff/', include('staff.urls', namespace='staff')),

    path('attendance/', include('attendance.urls', namespace='attendance')),
    path('demoschool/', include('demoschool.urls', namespace='demoschool')),
    path('portal/', include('portal.urls', namespace='portal')),
    path('quizes/', include('quizes.urls', namespace = 'quizes')),
    path('blog/', include('blog.urls', namespace = 'blog')),
    path('notification/', include('notification.urls', namespace = 'notification')),
    # path('demoschool/', include('demoschool.urls')),

    # path('ckeditor', include('ckeditor_uploader.urls')),    #for ckeditor image upload

    

#PATH FOR DOWNLOAD URL
   url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),

  


    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.urls import path
from django.conf.urls.static import static
from staff import views as user_views 
from django.contrib.auth import views as auth_views
from .views import StaffDetailView, StaffUpdateView, StaffDeleteView, StaffListView

app_name = 'staff'

urlpatterns = [
    path('staffform/', user_views.staffupdateprofile, name="staff_form"),
    # path('staff-academic/', user_views.staffacademic, name="staff-academic"),
    path('staff-list', user_views.stafflist, name="staff_list"),
     path('', StaffListView.as_view(), name="staff_list"),
    path('<str:id>/', StaffDetailView.as_view(), name="staff_detail"),
    path('<int:id>/update/', StaffUpdateView.as_view(), name="staff_update"),
    path('<int:id>/delete/', StaffDeleteView.as_view(), name="staff_delete"), 
    path('staff-pdf', user_views.staff_pdf, name="staff-pdf"),
    path('staff-csv', user_views.staff_csv, name="staff-csv"),

]

students/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from students import views as user_views 
from django.contrib.auth import views as auth_views
from students.views import (StudentListView,
                            StudentDetailView,
                            StudentCreateView,
                            StudentUpdateView,
                            StudentDeleteView,
                            MyStudentList,
)

app_name = 'students'

urlpatterns = [
    path('student-page/', user_views.studentpage, name="studentpage"),
    path('student-form/', user_views.studentupdateform, name="studentform"),
    path('', user_views.studentlist, name="student-list"),
    # path('pdf/<pk>/', user_views.student_render_pdf_view, name="student-pdf-view"),
    path('student-list/', StudentListView.as_view(), name="all-students"),
    path('<int:id>/', StudentDetailView.as_view(), name="students-detail"), 
    path('new/', StudentCreateView.as_view(), name="students-create"),
    path('<int:id>/update/', StudentUpdateView.as_view(), name="students-update"),
    path('<int:id>/delete/', StudentDeleteView.as_view(), name="students-delete"),  

    path('pdf/<pk>/', user_views.student_render_pdf_view, name="student-pdf-view"),
    path('test-view/', user_views.render_pdf_view, name="test-view"),

    path('student-pdf', user_views.mystudent_pdf, name="student-pdf"),
    path('student-csv', user_views.mystudent_csv, name="student-csv"),

    #for my rest_framework
    path('api-auth/', MyStudentList.as_view(), name="apiview"),
    
 


]

users/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views 
from django.contrib.auth import views as auth_views


app_name ='users'

urlpatterns = [
    path('register/', user_views.register, name="register"),
    path('student-staff/', user_views.student_staff, name="student_staff"),
    # path('login/', user_views.user_login, name="login"),
    path('dashboard/', user_views.users_home, name="users-dashboard"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('profile/', user_views.profile, name="profile"),
    path('logout/', user_views.user_logout, name='user_logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name="password_reset_confirm"),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name="password_reset_complete"),
    
   
]

users/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from .utils import generate_ref_code


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    middle_name = models.CharField(max_length=20, blank=True)
    address = models.CharField(max_length=20, blank=True, null=True)

    select = 'Select'
    southwest = 'SouthWest'
    southeast = 'SouthEast'
    southsouth = 'SouthSouth'
    northwest = 'NorthWest'
    northeast = 'NorthEast'
    northcentral = 'NorthCentral'
    
    region_origin = [
        ('Select', select),
        ('SouthWest', southwest),
        ('SouthEast', southeast),
        ('SouthSouth', southsouth),
        ('NorthWest', northwest),
        ('NorthEast', northeast),
        ('NorthCentral', northcentral),
    ]

    region_origin = models.CharField(max_length=15, choices=region_origin, default=select)

    male = 'male'
    female = 'female'
    
    gender_type = [
        ('male', male),
        ('female', female),
    ]

    gender= models.CharField(max_length=10, choices=gender_type, default=female)
    bio = models.TextField(max_length=150, blank=True)
    code = models.CharField(max_length=6, blank=True)
    phone = models.CharField(max_length=11, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    teacher = 'teacher'
    student = 'student'
    parent = 'parent'
    admin = 'admin'
 

    user_types = [
        (teacher, 'teacher'),
        (student, 'student'),
        (parent, 'parent'),
        (admin, 'admin'),
      
    ]

    user_type = models.CharField(max_length=15, choices=user_types, default=student)


#this function returns the profile name in the admin panel profile table
    def __str__ (self):
        return f'{self.user.username}-{self.code}'

    
    def save(self, *args, **kwargs):
        if self.code =="":
            code = generate_ref_code()
            self.code = code
        super().save(*args, **kwargs)


  

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['middle_name', 'phone', 'address', 'region_origin', 'image', ]
        widgets = {
            'dob': forms.DateInput(
                format=('%d/%m/%Y'),
                attrs={'class': 'form-control', 
                       'placeholder': 'Select a date',
                       'type': 'date'  # <--- IF I REMOVE THIS LINE, THE INITIAL VALUE IS DISPLAYED
                      }),
        }

users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.

@login_required
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'New user account has been created' )
            return redirect('student_staff')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your profile has been updated successfully')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }

    return render(request, 'users/profile.html', context)


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('users:profile'))
            else:
                return HttpResponse("ACCOUNT IS DEACTIVATED")

        else:
            return HttpResponse("Please use correct id and password")
    else:
        return render(request, 'users/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('pages:home'))


@login_required
def users_home(request):
    return render(request, 'portal/portal-home.html')



@login_required
def student_staff(request):
    return render(request, 'users/student_staff_register.html')

users/templates/users/login.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="keywords" content="" />
	<meta name="author" content="" />
	<meta name="robots" content="" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Schoolly : School Management System" />
	<meta property="og:title" content="Schoolly : School Management System" />
	<meta property="og:description" content="Schoolly :School Management System" />
	<meta property="og:image" content="#" />
	<meta name="format-detection" content="telephone=no">
	<!-- PAGE TITLE HERE -->
	<title>Schoolly Login</title>
	
	<!-- FAVICONS ICON -->
	<link rel="shortcut icon" type="image/png" href="{% static 'portal/images/logo.png' %}" />
    <link href="{% static 'portal/css/style.css' %}" rel="stylesheet">

</head>

<body class="vh-100">
    <div class="authincation h-100">
        <div class="container h-100">
            <div class="row justify-content-center h-100 align-items-center">
                <div class="col-md-6">
                    <div class="authincation-content">
                        <div class="row no-gutters">
                            <div class="col-xl-12">
                                <div class="auth-form">
									<div class="text-center mb-3">
										<a href="{% url 'pages:home' %}"><img src="{% static 'portal/images/logo-full.png' %}" alt=""></a>
									</div>
                                    <h4 class="text-center mb-4">Sign in to your account</h4>
                                    <form action="" method="post">
                                        {% csrf_token %}
                                        {{ form|crispy }}
                                        <div class="text-center mt-4">
                                            <button type="submit" value="submit" class="btn btn-primary btn-block">Sign in</button>
                                        </div>
                                        </form>
                                    <div class="new-account mt-3">
                                        
                                        <p><a href="{% url 'users:password_reset'%}">Forgot Password?</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!--**********************************
        Scripts
    ***********************************-->
    <!-- Required vendors -->
    <script src="{% static 'portal/vendor/global/global.min.js' %}"></script>
    <script src="{% static 'portal/js/custom.min.js' %}"></script>
    <script src="{% static 'portal/js/dlabnav-init.js' %}"></script>
	<script src="{% static 'portal/js/styleSwitcher.js' %}"></script>
</body>
</html>

users/templates/users/password_reset.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="keywords" content="" />
	<meta name="author" content="" />
	<meta name="robots" content="" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Schoolly : School Management Application" />
	<meta property="og:title" content="Schoolly : Modern School Management Application" />
	<meta property="og:description" content="Schoolly : Modern School Management Application" />
	<meta property="og:image" content="" />
	<meta name="format-detection" content="telephone=no">
	
	<!-- PAGE TITLE HERE -->
	{% block title %}<title>Schoolly Reset Password</title>{% endblock title %}
	
	<!-- FAVICONS ICON -->
	<link rel="shortcut icon" type="image/png" href="{% static 'portal/images/favicon.png' %}" />
    <link href="{% static 'portal/css/style.css' %}" rel="stylesheet">

</head>

<body class="vh-100">
    <div class="authincation h-100">
        <div class="container h-100">
            <div class="row justify-content-center h-100 align-items-center">
                <div class="col-md-6">
                    <div class="authincation-content">
                        <div class="row no-gutters">
                            <div class="col-xl-12">
                                <div class="auth-form">
									<div class="text-center mb-3">
										<a href="{% url 'pages:home' %}"><img src="{% static 'portal/images/logo-full.png' %}" alt=""></a>
									</div>
                                    {% block content_body %}
                                    <h4 class="text-center mb-4">Forgot Password</h4>
                                    <p>Enter your email address below</p>
                                    <form action="" method="POST">
                                        {% csrf_token %}
                                                    
                                        {{ form|crispy}}
                                        <div class="text-center mt-4">
                                            <button type="submit" value="submit" class="btn btn-primary btn-block">Reset Password</button>
                                        </div>
                                    </form>
                                    <div class="new-account mt-3">
                                        
                                        <p><a href="{% url 'pages:home'%}">Go back to home page</a></p>
                                    </div>
                                    {% endblock content_body %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!--**********************************
        Scripts
    ***********************************-->
    <!-- Required vendors -->
    <script src="{% static 'portal/vendor/global/global.min.js' %}"></script>
    <script src="{% static 'portal/js/custom.min.js' %}"></script>
    <script src="{% static 'portal/js/dlabnav-init.js' %}"></script>
	<script src="{% static 'portal/js/styleSwitcher.js' %}"></script>
</body>
</html>

users/templates/users/password_reset_complete.html
{% extends 'users/password_reset.html' %}
{% load static %}


{% block title %}<title>Schoolly - Password Reset Complete</title>{% endblock title %}

      {% block content_body %}                 
      
      <div class="col-lg-12 text-center">

                          <div class="alert alert-info">
                              
                        <h4 class="text-center mb-4"> Your password has been set.</h4>
                          </div>
                          <a href="{% url 'users:login' %}">Sign In Here</a>
                        <div class="border-top" pt-3>
                          <small class="text-muted">
                              Ensure you keep your account secure by protecting your password.
                          </small>
                      </div>
                  
                      </div>
          
          {% endblock content_body %}
                  

users/templates/users/password_reset_confirm.html
{% extends 'users/password_reset.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %}<title>Schoolly - Password Reset Confirm </title>{% endblock title %}

            {% block content_body %}
            <h4 class="text-center mb-4">Forgot Password</h4>
            <p>Enter a new password</p>
            <form action="" method="POST">
                {% csrf_token %}
                            
                {{ form|crispy}}
                <div class="text-center mt-4">
                    <button type="submit" value="submit" class="btn btn-primary btn-block">Reset Password</button>
                </div>
            </form>
            <div class="border-top" pt-3>
                <small class="text-muted">
                    Need An Account? <a class="ml-2" href="{% url 'users:register' %}">Register</a>
                </small>
            </div>
        
        </div>
        {% endblock content_body %}
    

users/templates/users/password_reset_done.html
{% extends 'users/password_reset.html' %}
{% load static %}


    
{% block title %}<title>Schoolly - Password Reset Done</title>{% endblock title %}
{% block content_body %}
    <div class="col-lg-12 text-center">

        <div class="alert alert-info">
            
    <h4 class="text-center mb-4"> An Email has been sent with instructions to reset your password</h4>
    <p>Check the Spam box if you do not see it in your inbox</p>
        </div>
    

    </div>
    
    {% endblock content_body %}

users/templates/users/register.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="keywords" content="" />
	<meta name="author" content="" />
	<meta name="robots" content="" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Schoolly : School Management System" />
	<meta property="og:title" content="Schoolly : School Management System" />
	<meta property="og:description" content="Schoolly :School Management System" />
	<meta property="og:image" content="#" />
	<meta name="format-detection" content="telephone=no">
	<!-- PAGE TITLE HERE -->
	<title>Schoolly Register New User </title>
	
	<!-- FAVICONS ICON -->
	<link rel="shortcut icon" type="image/png" href="{% static 'portal/images/logo.png' %}" />
    <link href="{% static 'portal/css/style.css' %}" rel="stylesheet">

</head>

<body class="vh-100">
    <div class="authincation h-100">
        <div class="container h-100">
            <div class="row justify-content-center h-100 align-items-center">
                <div class="col-md-6">
                    <div class="authincation-content">
                        <div class="row no-gutters">
                            <div class="col-xl-12">
                                <div class="auth-form">
									<div class="text-center mb-2">
										<a href="{% url 'pages:home' %}"><img src="{% static 'portal/images/logo-full.png' %}" alt=""></a>
									</div>
                                    <h6 class="text-center mb-2">Register New User</h2>
                                    {% if messages %}
                                    {% for message in messages %}
                                    <div class ="alert alert-{{ message.tags }}">{{ message }}</div>
                                    {% endfor%}
                                    {% endif%}
                                    <div class="new-account mt-3">
                                        <p>Already have an account? <a class="text-primary" href="{% url 'users:login' %}">Sign in</a></p>
                                    </div>
                                    
                                       
                                    <form  action="" method="post">
                                        {% csrf_token %}
                                        
                                       {{ form|crispy }}
                                       <div class="text-center mt-4">
                                        <button type="submit" value="submit" class="btn btn-primary btn-block">Sign me up</button>
                                    </div>
                                    </form>                                   
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<!--**********************************
	Scripts
***********************************-->
<!-- Required vendors -->
<script src="{% static 'portal/vendor/global/global.min.js' %}"></script>
<script src="{% static 'portal/js/custom.min.js' %}"></script>
<script src="{% static 'portal/js/dlabnav-init.js' %}"></script>
<script src="{% static 'portal/js/styleSwitcher.js' %}"></script>
</body>
</html>

users/templates/users/student_staff_register.html
{% extends 'portal/portal-home.html' %}
{% load static %}

{% block title %}<title> Schoolly - Register Staff Students </title>{% endblock title %}

{% block content_body %}
<div class="content-body">
    <div class="container-fluid">
        <div class="row page-titles">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active"><a href="javascript:void(0)">Register Students or Staff</a></li>
                <li class="breadcrumb-item"><a href="javascript:void(0)">Card</a></li>
            </ol>
        </div>
        <div class="row">
            <div class="col-xl-6">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">New Student Registration</h5>
                    </div>
                    <div class="card-body">
                        <p class="card-text">This is a wider card with supporting text and below as a natural lead-in to the additional content. This content is a little <br> bit longer. Some quick example text to build the bulk
                        </p>
                    </div>
                    <div class="card-footer d-sm-flex justify-content-between align-items-center">
                        <div class="card-footer-link mb-4 mb-sm-0">
                            <p class="card-text text-dark d-inline">Last updated 3 mins ago</p>
                        </div>

                        <a href="{% url 'students:students-create' %}" class="btn btn-primary">Register Student</a>
                    </div>
                </div>
            </div>
            <div class="col-xl-6">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">New Staff Registration</h5>
                    </div>
                    <div class="card-body">
                        <p class="card-text">This is a wider card with supporting text and below as a natural lead-in to the additional content. This content is a little <br> bit longer. Some quick example text to build the bulk</p>
                    </div>
                    <div class="card-footer d-sm-flex justify-content-between align-items-center">
                        <div class="card-footer-link mb-4 mb-sm-0">
                            <p class="card-text text-dark d-inline">Last updated 3 mins ago</p>
                        </div>

                        <a href="{% url 'staff:staff_form' %}" class="btn btn-primary">Register Staff</a>
                    </div>
                </div>
            </div>

            <div class="col-xl-4">
                <div class="card">
                    <div class="card-header">
                        <p class="card-title">Register Another User</p>
                    </div>

                    <a href="{% url 'register' %}" class="btn btn-primary">Register Another User</a>
                </div>
                    </div>
           
            </div>
            </div>


        </div>
    </div>
</div>
{% endblock content_body %}


{% block scripts %}
<script src="{% static 'portal/vendor/global/global.min.js' %}"></script>
<script src="{% static 'portal/vendor/jquery-nice-select/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'portal/js/custom.min.js' %}"></script>
<script src="{% static 'portal/js/dlabnav-init.js' %}"></script>
<script src="{% static 'portal/js/demo.js' %}"></script>
<script src="{% static 'portal/js/styleSwitcher.js' %}"></script>
{% endblock scripts %}