blog/urls.py
from django.urls import path
from .views import (
    PostDetailView,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView
)
from . import views

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='blog_home'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('new/', PostCreateView.as_view(), name='post_create'),
    path('<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
]

notification/urls.py
from django.urls import path
from . import views
from notification import views as notification_views
from .views import NotificationListView, NotificationDetailView, NotificationCreateView



app_name = 'notification'

urlpatterns = [
    path('', views.NotificationListView.as_view(), name="mail-list"),
    path('self-mail/', notification_views.view_self_notification, name="mail-self"),
    path('self-mail/<int:pk>/', NotificationDetailView.as_view(), name='mail-detail'),
    path('new-mail/', NotificationCreateView.as_view(), name='new-mail'),
    path('calendar/', notification_views.school_calendar, name="calendar"),
    

    
      
   
]

schoolly/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve






urlpatterns = [
    path('admin/', admin.site.urls),
    path('curriculum/', include('curriculum.urls', namespace='curriculum')),
    path('', include('pages.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('users/', include('users.urls', namespace='users')),
   
    path('results/', include('results.urls', namespace='results')),
    path('students/', include('students.urls', namespace='students')),
    path('staff/', include('staff.urls', namespace='staff')),

    path('attendance/', include('attendance.urls', namespace='attendance')),
    path('demoschool/', include('demoschool.urls', namespace='demoschool')),
    path('portal/', include('portal.urls', namespace='portal')),
    path('quizes/', include('quizes.urls', namespace = 'quizes')),
    path('blog/', include('blog.urls', namespace = 'blog')),
    path('notification/', include('notification.urls', namespace = 'notification')),
    # path('demoschool/', include('demoschool.urls')),

    # path('ckeditor', include('ckeditor_uploader.urls')),    #for ckeditor image upload

    

#PATH FOR DOWNLOAD URL
   url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),

  


    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notification/models.py
from time import timezone
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Notification(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    recipient = models.ManyToManyField(User, related_name='send_mail')
    subject = models.CharField(max_length=100)
    content = models.TextField(max_length=1000)
    attachement = models.CharField(max_length=1000)
    date_sent = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.sender}'

    def get_absolute_url(self, *args, **kwargs):
        return reverse('notification:mail-self')



class MailReply(models.Model):
    notification_name = models.ForeignKey(Notification, on_delete=models.CASCADE, related_name='replies')
    reply_body = models.TextField(max_length=500)
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "reply to" + str(self.sender.sender)

notification/forms.py
from django import forms
from.models import Notification



class MailForm(forms.ModelForm):
   
    class Meta:
        
        model = Notification
        fields = ('recipient', 'subject', 'content')


# class ReplyMailForm(forms.ModelForm):
#     class Meta:
#         model = ReplyMailForm
#         fields = ('reply_body',)

#         widgets = {
#             'reply_body': forms.Textarea(attrs={'class':'form-control', 'rows':2, 'cols':10}),

notification/views.py
from django.conf import settings
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import DetailView, ListView, DeleteView, CreateView
from django.http import Http404, HttpResponseRedirect, HttpResponse
from notification.models import Notification
from .forms import MailForm
from django.contrib.auth.models import User
import os
from portal.models import SchoolCalendar
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger



class NotificationListView(ListView):
    model = Notification
    template_name = 'notification/mail_list.html'
    context_object_name = 'notification'


class NotificationDetailView(DetailView):
    model = Notification
    template_name = 'notification/mail_detail.html'
    context_object_name = 'mails'


class NotificationCreateView(CreateView):
    form_class = MailForm
    context_object_name = 'notification'
    model = Notification
    template_name = 'notification/send_mail.html'

    def form_valid(self, form, *args, **kwargs):
        form.instance.sender = self.request.user
        return super().form_valid(form)



class NotificationDeleteView(DeleteView):
    model = Notification
    template_name = 'notification/notification_detail.html'


@login_required
def view_self_notification(request, **kwargs):
# this issue was solved by me.
    try:     
        mymail = Notification.objects.filter(recipient=User.objects.get(username=request.user))
    
        context = {
            'mymail':mymail
            
        }    
    
        return render(request, 'notification/view_self_mail.html', context)

    except Notification.DoesNotExist:
        return HttpResponse('You are not a registered')
        

# FUNCTION FOR DOWNLOADING FILE
def download(request,path):
    file_path=os.path.join(settings.MEDIA_ROOT,path)
    if os.path.exists(file_path):
        with open(file_path, 'rb')as fh:
            response=HttpResponse(fh.read(),content_type="application/file")
            response['Content-Disposition']='inline;filename='+os.path.basename(file_path)
            return response

    raise Http404


@login_required
def school_calendar(request):

    queryset = SchoolCalendar.objects.all().order_by("-id")
    page = request.GET.get('page', 1)
    paginator = Paginator(queryset, 4)
    try:
        events = paginator.page(page)
    except PageNotAnInteger:
        events = paginator.page(1)
    except EmptyPage:
        events = paginator.page(paginator.num_pages)
    
    context = {
       
        'queryset': queryset,
        'events':events,
    }
    return render(request, 'notification/school_calendar.html', context)

notification/templates/notification/mail_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for mail in notification %}
        {{ mail.sender }}<br>
        {{ mail.subject }}<br>
        {{ mail.date_sent }}<br>
        {{ mail.recipient }}<br>
   
        <hr>
    {% endfor %}
</body>
</html>

notification/templates/notification/mail_template_header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    heloooo
</body>
</html>

notification/templates/notification/send_mail.html
{% extends 'portal/portal-home.html' %}
{% load static%}
{% load crispy_forms_tags %}

{% block content_body %}

<div class="content-body">
    <div class="container-fluid">
        
        <div class="row page-titles">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active"><a href="javascript:void(0)">Email</a></li>
                <li class="breadcrumb-item"><a href="javascript:void(0)">Compose</a></li>
            </ol>
        </div>
        
        <!-- row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="email-left-box px-0 mb-3">
                            <div class="p-0">
                                <a href="{% url 'notification:new-mail' %}" class="btn btn-primary btn-block">Compose</a>
                            </div>
                            <div class="mail-list rounded mt-4">
                                <a href="email-inbox.html" class="list-group-item active"><i
                                        class="fa fa-inbox font-18 align-middle me-2"></i> Inbox <span
                                        class="badge badge-primary badge-sm float-end">12</span> </a>
                                <a href="javascript:void()" class="list-group-item"><i
                                        class="fa fa-paper-plane font-18 align-middle me-2"></i>Sent</a> <a href="javascript:void()" class="list-group-item"><i class="fas fa-star me-2"></i>Important <span
                                        class="badge badge-danger text-white badge-sm float-end">7</span>
                                </a>
                                <a href="javascript:void()" class="list-group-item"><i
                                        class="mdi mdi-file-document-box font-18 align-middle me-2"></i>Draft</a><a href="javascript:void()" class="list-group-item"><i
                                        class="fa fa-trash font-18 align-middle me-2"></i>Trash</a>
                            </div>
                            <div class="mail-list rounded overflow-hidden mt-4">
                                <div class="intro-title d-flex justify-content-between my-0">
                                    <h5>Categories</h5>
                                    <i class="fa fa-chevron-down"></i>
                                </div>
                                <a href="email-inbox.html" class="list-group-item"><span class="icon-warning"><i
                                            class="fa fa-circle"></i></span>
                                    Work </a>
                                <a href="email-inbox.html" class="list-group-item"><span class="icon-primary"><i
                                            class="fa fa-circle"></i></span>
                                    Private </a>
                                <a href="email-inbox.html" class="list-group-item"><span class="icon-success"><i
                                            class="fa fa-circle"></i></span>
                                    Support </a>
                                <a href="email-inbox.html" class="list-group-item"><span class="icon-dpink"><i
                                            class="fa fa-circle"></i></span>
                                    Social </a>
                            </div>
                        </div>
                        <div class="email-right-box ms-0 ms-sm-4 ms-sm-0">
                            <div class="toolbar mb-4" role="toolbar">
                                <div class="btn-group mb-1">
                                    <button type="button" class="btn btn-primary light px-3"><i class="fa fa-archive"></i></button>
                                    <button type="button" class="btn btn-primary light px-3"><i class="fa fa-exclamation-circle"></i></button>
                                    <button type="button" class="btn btn-primary light px-3"><i class="fa fa-trash"></i></button>
                                </div>
                                <div class="btn-group mb-1">
                                    <button type="button" class="btn btn-primary light dropdown-toggle px-3" data-bs-toggle="dropdown">
                                        <i class="fa fa-folder"></i> <b class="caret m-l-5"></b>
                                    </button>
                                    <div class="dropdown-menu"> 
                                        <a class="dropdown-item" href="javascript: void(0);">Social</a> 
                                        <a class="dropdown-item" href="javascript: void(0);">Promotions</a> 
                                        <a class="dropdown-item" href="javascript: void(0);">Updates</a>
                                        <a class="dropdown-item" href="javascript: void(0);">Forums</a>
                                    </div>
                                </div>
                                <div class="btn-group mb-1">
                                    <button type="button" class="btn btn-primary light dropdown-toggle px-3" data-bs-toggle="dropdown">
                                        <i class="fa fa-tag"></i> <b class="caret m-l-5"></b>
                                    </button>
                                    <div class="dropdown-menu"> 
                                        <a class="dropdown-item" href="javascript: void(0);">Updates</a> 
                                        <a class="dropdown-item" href="javascript: void(0);">Social</a> 
                                        <a class="dropdown-item" href="javascript: void(0);">Promotions</a>
                                        <a class="dropdown-item" href="javascript: void(0);">Forums</a>
                                    </div>
                                </div>
                                <div class="btn-group mb-1">
                                    <button type="button" class="btn btn-primary light dropdown-toggle v" data-bs-toggle="dropdown">More <span class="caret m-l-5"></span>
                                    </button>
                                    <div class="dropdown-menu"> <a class="dropdown-item" href="javascript: void(0);">Mark as Unread</a> <a class="dropdown-item" href="javascript: void(0);">Add to Tasks</a>
                                        <a class="dropdown-item" href="javascript: void(0);">Add Star</a> <a class="dropdown-item" href="javascript: void(0);">Mute</a>
                                    </div>
                                </div>
                            </div>
                            <div class="compose-content">
                                <form action="#" method="POST">
                                    {% csrf_token %}
                                    {{ form|crispy}}
                                    <h5 class="mb-4"><i class="fa fa-paperclip"></i> Attachment</h5>
                                    <input name="file" type="file" multiple />
                                    <div class="text-start mt-4 mb-3">
                                        <button class="btn btn-primary btn-sl-sm me-2" type="submit "><span class="me-2"><i class="fa fa-paper-plane"></i></span>Send</button>
                                        <button class="btn btn-danger light btn-sl-sm" type="button"><span class="me-2"><i class="fa fa-times"></i></span>Discard</button>
                                    </div>
                                </form>
                                
                            </div>
                           
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

{% endblock content_body %}

notification/templates/notification/view_self_mail.html
{% extends 'portal/portal-home.html' %}
{% load static%}

{% block content_body %}

<div class="content-body">
    <div class="container-fluid">
        <div class="row page-titles">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active"><a href="javascript:void(0)">Email</a></li>
                <li class="breadcrumb-item"><a href="javascript:void(0)">Inbox</a></li>
            </ol>
        </div>
        <!-- row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="email-left-box px-0 mb-3">
                            <div class="p-0">
                                <a href="{% url 'notification:new-mail' %}" class="btn btn-primary btn-block">Compose</a>
                            </div>
                            <div class="mail-list rounded mt-4">
                                <a href="email-inbox.html" class="list-group-item active"><i
                                        class="fa fa-inbox font-18 align-middle me-2"></i> Inbox <span
                                        class="badge badge-primary badge-sm float-end">198</span> </a>
                                <a href="javascript:void()" class="list-group-item"><i
                                        class="fa fa-paper-plane font-18 align-middle me-2"></i>Sent</a> <a href="javascript:void()" class="list-group-item"><i
                                        class="fa fa-star font-18 align-middle me-2"></i>Important <span
                                        class="badge badge-danger text-white badge-sm float-end">47</span>
                                </a>
                                <a href="javascript:void()" class="list-group-item"><i
                                        class="mdi mdi-file-document-box font-18 align-middle me-2"></i>Draft</a><a href="javascript:void()" class="list-group-item"><i
                                        class="fa fa-trash font-18 align-middle me-2"></i>Trash</a>
                            </div>
                            <div class="mail-list rounded overflow-hidden mt-4">
                                <div class="intro-title d-flex justify-content-between my-0">
                                    <h5>Categories</h5>
                                    <i class="icon-arrow-down" aria-hidden="true"></i>
                                </div>
                                <a href="email-inbox.html" class="list-group-item"><span class="icon-warning"><i
                                            class="fa fa-circle" aria-hidden="true"></i></span>
                                    Work </a>
                                <a href="email-inbox.html" class="list-group-item"><span class="icon-primary"><i
                                            class="fa fa-circle" aria-hidden="true"></i></span>
                                    Private </a>
                                <a href="email-inbox.html" class="list-group-item"><span class="icon-success"><i
                                            class="fa fa-circle" aria-hidden="true"></i></span>
                                    Support </a>
                                <a href="email-inbox.html" class="list-group-item"><span class="icon-dpink"><i
                                            class="fa fa-circle" aria-hidden="true"></i></span>
                                    Social </a>
                            </div>
                        </div>
                        <div class="email-right-box ms-0 ms-sm-4 ms-sm-0">
                            <div role="toolbar" class="toolbar ms-1 ms-sm-0">
                                <div class="btn-group mb-1">
                                    <div class="form-check custom-checkbox">
                                        <input type="checkbox" class="form-check-input" id="checkAll">
                                        <label class="form-check-label" for="checkAll"></label>
                                    </div>
                                </div>
                                <div class="btn-group mb-1">
                                    <button class="btn btn-primary light px-3" type="button"><i class="ti-reload"></i>
                                    </button>
                                </div>
                                <div class="btn-group mb-1">
                                    <button aria-expanded="false" data-bs-toggle="dropdown" class="btn btn-primary px-3 light dropdown-toggle" type="button">More <span
                                            class="caret"></span>
                                    </button>
                                    <div class="dropdown-menu"> <a href="javascript: void(0);" class="dropdown-item">Mark as Unread</a> <a href="javascript: void(0);" class="dropdown-item">Add to Tasks</a>
                                        <a href="javascript: void(0);" class="dropdown-item">Add Star</a> <a href="javascript: void(0);" class="dropdown-item">Mute</a>
                                    </div>
                                </div>
                            </div>
                            <div class="email-list mt-3">
                                {% for mail in mymail %}
                                <div class="message">
                                  
                                    <div>
                                        <div class="d-flex message-single">
                                            <div class="ps-1 align-self-center">
                                                <div class="form-check custom-checkbox">
                                                    <input type="checkbox" class="form-check-input" id="checkbox2">
                                                    <label class="form-check-label" for="checkbox2"></label>
                                                </div>
                                            </div>
                                            <div class="ms-2">
                                                <button class="border-0 bg-transparent align-middle p-0"><i
                                                        class="fa fa-star" aria-hidden="true"></i></button>
                                            </div>
                                        </div>

                                        <a href="{% url 'notification:mail-detail' mail.pk %}" class="col-mail col-mail-2">
                                            <div class="subject"> From: {{ mail.sender }} - Subject: {{ mail.subject }} </div>
                                            <div class="date">{{ mail.date_sent }}</div>
                                        </a>
                                    </div>
                                </div>
                                               {% endfor %}                                    
                                
                              
                            <!-- panel -->
                           <!-- PAGINATION SHOULD BE HERE OLU-->
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock content_body %}
<!--**********************************
    Content body end
***********************************-->